[build]
  command = "npm install && cd netlify/functions && npm install"
  functions = "netlify/functions"
  publish = "."

[build.environment]
  NODE_VERSION = "18"
  NPM_FLAGS = "--no-audit --no-fund"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/api/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[functions]
  node_bundler = "esbuild"
  external_node_modules = ["@distube/ytdl-core", "buffer", "events", "web-streams-polyfill"]
  included_files = ["netlify/functions/node_modules/@distube/ytdl-core/**/*"]
  
[functions.environment]
  NODE_OPTIONS = "--experimental-fetch"

[functions.api]
  timeout = 30
